ExponentialRetryRequestExecuter Error: 0 : 21:34:29.8654021 : 1-testhost : Unexpected exception: ReportPortal.Client.ReportPortalException: Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch
 ---> System.Net.Http.HttpRequestException: Response message: Bad Gateway
   --- End of inner exception stack trace ---
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
TestReporter Error: 0 : 21:34:29.8734527 : 1-testhost : System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch)
 ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch
 ---> System.Net.Http.HttpRequestException: Response message: Bad Gateway
   --- End of inner exception stack trace ---
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Start>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
TestReporter Error: 0 : 21:34:29.8750488 : 1-testhost : System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch)
 ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch
 ---> System.Net.Http.HttpRequestException: Response message: Bad Gateway
   --- End of inner exception stack trace ---
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Start>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
TestReporter Error: 0 : 21:34:29.8763659 : 1-testhost : System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch)
 ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch
 ---> System.Net.Http.HttpRequestException: Response message: Bad Gateway
   --- End of inner exception stack trace ---
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Start>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
TestReporter Error: 0 : 21:34:29.8779163 : 1-testhost : System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch)
 ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch
 ---> System.Net.Http.HttpRequestException: Response message: Bad Gateway
   --- End of inner exception stack trace ---
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Start>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
TestReporter Error: 0 : 21:34:29.8792270 : 1-testhost : System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch)
 ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch
 ---> System.Net.Http.HttpRequestException: Response message: Bad Gateway
   --- End of inner exception stack trace ---
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Start>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
TestReporter Error: 0 : 21:34:29.8803358 : 1-testhost : System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch)
 ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch
 ---> System.Net.Http.HttpRequestException: Response message: Bad Gateway
   --- End of inner exception stack trace ---
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Start>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
TestReporter Error: 0 : 21:34:38.7417209 : 1-testhost : System.Exception: Cannot finish test item due starting item failed.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch)
 ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch
 ---> System.Net.Http.HttpRequestException: Response message: Bad Gateway
   --- End of inner exception stack trace ---
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Start>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
TestReporter Error: 0 : 21:34:38.7448503 : 1-testhost : System.Exception: Cannot finish test item due starting item failed.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch)
 ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch
 ---> System.Net.Http.HttpRequestException: Response message: Bad Gateway
   --- End of inner exception stack trace ---
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Start>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
TestReporter Error: 0 : 21:34:38.7555827 : 1-testhost : System.Exception: Cannot finish test item due starting item failed.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch)
 ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch
 ---> System.Net.Http.HttpRequestException: Response message: Bad Gateway
   --- End of inner exception stack trace ---
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Start>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
TestReporter Error: 0 : 21:34:38.7571867 : 1-testhost : System.Exception: Cannot finish test item due starting item failed.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch)
 ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch
 ---> System.Net.Http.HttpRequestException: Response message: Bad Gateway
   --- End of inner exception stack trace ---
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Start>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
TestReporter Error: 0 : 21:34:38.7820526 : 1-testhost : System.Exception: Cannot finish test item due starting item failed.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch)
 ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch
 ---> System.Net.Http.HttpRequestException: Response message: Bad Gateway
   --- End of inner exception stack trace ---
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Start>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at ReportPortal.Shared.Reporter.LaunchReporter.Sync()
   at ReportPortal.NUnitExtension.ReportPortalListener.FinishRun(String report) in C:\projects\agent-net-nunit\src\ReportPortal.NUnitExtension\ReportPortalListener.Launch.cs:line 111
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
TestReporter Error: 0 : 21:34:38.7836536 : 1-testhost : System.Exception: Cannot finish test item due starting item failed.
 ---> System.AggregateException: One or more errors occurred. (Cannot start test item due parent failed to start.)
 ---> System.Exception: Cannot start test item due parent failed to start.
 ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch)
 ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch
 ---> System.Net.Http.HttpRequestException: Response message: Bad Gateway
   --- End of inner exception stack trace ---
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Start>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at ReportPortal.Shared.Reporter.LaunchReporter.Sync()
   at ReportPortal.NUnitExtension.ReportPortalListener.FinishRun(String report) in C:\projects\agent-net-nunit\src\ReportPortal.NUnitExtension\ReportPortalListener.Launch.cs:line 111
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
LaunchReporter Error: 0 : 21:34:38.7912111 : 1-testhost : System.Exception: Cannot finish launch due starting launch failed.
 ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch)
 ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: BadGateway (502) POST http://localhost:8080/api/v1/automation_demo/launch
 ---> System.Net.Http.HttpRequestException: Response message: Bad Gateway
   --- End of inner exception stack trace ---
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Start>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at ReportPortal.Shared.Reporter.LaunchReporter.Sync()
   at ReportPortal.NUnitExtension.ReportPortalListener.FinishRun(String report) in C:\projects\agent-net-nunit\src\ReportPortal.NUnitExtension\ReportPortalListener.Launch.cs:line 111
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
